export const FETCH_ALL_CHATS_REQUESTED = 'FETCH_ALL_CHATS_REQUESTED'
export const FETCH_ALL_CHATS_SUCCESS = 'FETCH_ALL_CHATS_SUCCESS'
export const FETCH_ALL_CHATS_FAILED = 'FETCH_ALL_CHATS_FAILED'

export const FETCH_MY_CHATS_REQUESTED = 'FETCH_MY_CHATS_REQUESTED'
export const FETCH_MY_CHATS_SUCCESS = 'FETCH_MY_CHATS_SUCCESS'
export const FETCH_MY_CHATS_FAILED = 'FETCH_MY_CHATS_FAILED'

export const FETCH_CHAT_REQUESTED = 'FETCH_CHAT_REQUESTED'
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS'
export const FETCH_CHAT_FAILED = 'FETCH_CHAT_FAILED'

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'
export const UNSET_ACTIVE_CHAT = 'UNSET_ACTIVE_CHAT'
