export const FETCH_ALL_CHATS_REQUESTED = 'FETCH_ALL_CHATS_REQUESTED'
export const FETCH_ALL_CHATS_SUCCESS = 'FETCH_ALL_CHATS_SUCCESS'
export const FETCH_ALL_CHATS_FAILED = 'FETCH_ALL_CHATS_FAILED'

export const FETCH_MY_CHATS_REQUESTED = 'FETCH_MY_CHATS_REQUESTED'
export const FETCH_MY_CHATS_SUCCESS = 'FETCH_MY_CHATS_SUCCESS'
export const FETCH_MY_CHATS_FAILED = 'FETCH_MY_CHATS_FAILED'

export const FETCH_CHAT_REQUESTED = 'FETCH_CHAT_REQUESTED'
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS'
export const FETCH_CHAT_FAILED = 'FETCH_CHAT_FAILED'

export const CREATE_CHAT_REQUESTED = 'CREATE_CHAT_REQUESTED'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_FAILED = 'CREATE_CHAT_FAILED'

export const JOIN_CHAT_REQUESTED = 'JOIN_CHAT_REQUESTED'
export const JOIN_CHAT_SUCCESS = 'JOIN_CHAT_SUCCESS'
export const JOIN_CHAT_FAILED = 'JOIN_CHAT_FAILED'

export const LEAVE_CHAT_REQUESTED = 'LEAVE_CHAT_REQUESTED'
export const LEAVE_CHAT_SUCCESS = 'LEAVE_CHAT_SUCCESS'
export const LEAVE_CHAT_FAILED = 'LEAVE_CHAT_FAILED'

export const DELETE_CHAT_REQUESTED = 'DELETE_CHAT_REQUESTED'
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS'
export const DELETE_CHAT_FAILED = 'DELETE_CHAT_FAILED'

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'
export const UNSET_ACTIVE_CHAT = 'UNSET_ACTIVE_CHAT'
