export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
export const REGISTER_FAILED = 'REGISTER_FAILED'