export const SOCKETS_CONNECTION_REQUEST = 'SOCKETS_CONNECTION_REQUEST';
export const SOCKETS_CONNECTION_SUCCESS = 'SOCKETS_CONNECTION_SUCCESS';
export const SOCKETS_CONNECTION_FAILED = 'SOCKETS_CONNECTION_FAILED';
export const SOCKETS_CONNECTION_MISSING = 'SOCKETS_CONNECTION_MISSING';

export const MOUNT_CHAT = 'MOUNT_CHAT';
export const UN_MOUNT_CHAT = 'UN_MOUNT_CHAT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const RECEIVE_NEW_CHAT = 'RECEIVE_NEW_CHAT';
export const RECEIVE_DELETED_CHAT = 'RECEIVE_DELETED_CHAT';
